name: hfc-policy-outcomes
channels:
  - chrisroadmap
  - conda-forge
  - defaults
dependencies:
  - climateforcing
  - jupyter
  - nbstripout
  - fair
  - h5py
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - scipy
  - tqdm
